[env:pico32]
platform = espressif32@3.5.0
board = pico32
framework = arduino
lib_deps = 
    SPI
    Wire
    smartphone-companions/ESP32 BLE ANCS Notifications@^0.0.1
    olikraus/U8g2@^2.35.19
    h2zero/NimBLE-Arduino@^1.4.2
    fbiego/ESP32Time@^2.0.6
